DROP TABLE IF EXISTS CAR;
DROP TABLE IF EXISTS CAR_ORDER;

CREATE TABLE CAR
(
    CAR_ID         INT         NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CAR_MODEL      VARCHAR(15) NOT NULL,
    YEAR_OF_ISSUE  INT         NOT NULL,
    CAR_COLOR      VARCHAR(15) NOT NULL,
    PRICE_PER_DAY  DOUBLE      NOT NULL,
    LEASED BOOLEAN DEFAULT               FALSE
);

CREATE TABLE CAR_ORDER
(
    CAR_ORDER_ID        INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    RENTERS_NAME        VARCHAR(255) NOT NULL,
    DATE_LEASED         DATE         NOT NULL,
    RENT_STATUS BOOLEAN DEFAULT      TRUE,
    CAR_REPAIR_BILL     DOUBLE,
    INFO_ABOUT_DAMAGE   VARCHAR(255),
    REJECTION_REASON    VARCHAR(255),
    CAR_ID              INT          NOT NULL,


    CONSTRAINT CAR_CAR_ORDER_FK FOREIGN KEY (CAR_ID) REFERENCES CAR(CAR_ID) ON UPDATE CASCADE
);