INSERT INTO CAR(CAR_ID,CAR_MODEL,YEAR_OF_ISSUE,CAR_COLOR,PRICE_PER_DAY,LEASED) VALUES (1, 'Audi', 2010, 'Black', 20.0, FALSE );
INSERT INTO CAR(CAR_ID,CAR_MODEL,YEAR_OF_ISSUE,CAR_COLOR,PRICE_PER_DAY,LEASED) VALUES (2, 'BMW', 2000, 'Black', 10.0, FALSE );
INSERT INTO CAR(CAR_ID,CAR_MODEL,YEAR_OF_ISSUE,CAR_COLOR,PRICE_PER_DAY,LEASED) VALUES (3, 'Ford', 2006, 'Red', 18.0, FALSE );
INSERT INTO CAR(CAR_ID,CAR_MODEL,YEAR_OF_ISSUE,CAR_COLOR,PRICE_PER_DAY,LEASED) VALUES (4, 'Mazda', 2018, 'White', 15.0, FALSE );

INSERT INTO CAR_ORDER(CAR_ORDER_ID,RENTERS_NAME,DATE_LEASED,RENT_STATUS,CAR_REPAIR_BILL,INFO_ABOUT_DAMAGE,REJECTION_REASON,CAR_ID) VALUES (1,'Aleinikau','2020-12-05',TRUE, 0.0,null,null,1 );
INSERT INTO CAR_ORDER(CAR_ORDER_ID,RENTERS_NAME,DATE_LEASED,RENT_STATUS,CAR_REPAIR_BILL,INFO_ABOUT_DAMAGE,REJECTION_REASON,CAR_ID) VALUES (2,'Budik','2020-11-08',TRUE, 0.0,null,null,2);
INSERT INTO CAR_ORDER(CAR_ORDER_ID,RENTERS_NAME,DATE_LEASED,RENT_STATUS,CAR_REPAIR_BILL,INFO_ABOUT_DAMAGE,REJECTION_REASON,CAR_ID) VALUES (3,'Kot','2020-08-05',TRUE, 0.0,null,null,3 );
INSERT INTO CAR_ORDER(CAR_ORDER_ID,RENTERS_NAME,DATE_LEASED,RENT_STATUS,CAR_REPAIR_BILL,INFO_ABOUT_DAMAGE,REJECTION_REASON,CAR_ID) VALUES (4,'Kobrinetc','2020-01-05',TRUE, 0.0,null,null,4);